services:

  db:
    image: mysql:8.0
    container_name: qless_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: qless
      MYSQL_USER: qless_user
      MYSQL_PASSWORD: qless_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpw"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: qless_redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: qless_web
    restart: always

    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 15 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql_data: