# Generated by Django 6.0.5 on 2026-05-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_venue_verified',
            field=models.BooleanField(default=False),
        ),
    ]
